In [1]:
import numpy as np
ipData = np.array([[2,9],[1,5],[3,6]], dtype=float) 
expectedOp=np.array ([[92], [86], [89]], dtype=float) 
ipData /= np.amax(ipData, axis=0)
expectedOp/=100 
def sigmoid(x):
    return 1/(1+np.exp(-x)) 
def derivative_sigmoid(x):
    return x*(1-x)
epoch=20
learning_rate = 0.5
iplayerNeurons = 2 
hiddenlayerNeurons=3 
oplayerNeurons = 1 
hiddenlayerWt=np.random.uniform(size=(iplayerNeurons,
                                            hiddenlayerNeurons)) 
hiddenlayerBias = np.random.uniform(size=(1, hiddenlayerNeurons)) 
oplayerWt=np.random.uniform(size= (hiddenlayerNeurons,
                                             oplayerNeurons ))  
outputlayer_bias = np.random.uniform(size=(1, oplayerNeurons)) 
for i in range(epoch):
    hiddenlayerIp = np.dot(ipData, hiddenlayerWt) + hiddenlayerBias 
    #hiddenlayerIp = hiddenlayerIp + 
    hiddenlayerOp = sigmoid(hiddenlayerIp) 
    
    outputlayerIp = np.dot(hiddenlayerOp, oplayerWt) 
    outputlayerIp = outputlayerIp + outputlayer_bias
    outputlayerOp=sigmoid(outputlayerIp)
     
    outputlayerErr=expectedOp-outputlayerOp 
    outputlayerGradient=derivative_sigmoid(outputlayerOp) 
    outputlayerErr_correction = outputlayerErr* outputlayerGradient
   
    hiddenlayer_error = outputlayerErr_correction.dot (oplayerWt. T) 
    hiddenlayer_gradient=derivative_sigmoid(hiddenlayerOp) 
    hiddenlayer_error_correction=hiddenlayer_error*hiddenlayer_gradient
    
    oplayerWt += hiddenlayerOp.T.dot(outputlayerErr_correction) * learning_rate 
    hiddenlayerWt += ipData.T.dot(hiddenlayer_error_correction)*learning_rate
    print(i,"th iteration ",hiddenlayerWt)
    
print("Input : ", ipData)
print("Expected Output :", expectedOp)
print("actual output: ",outputlayerOp)

0 th iteration  [[0.20127245 0.60671963 0.60013375]
 [0.338566   0.30360757 0.63976345]]
1 th iteration  [[0.20214164 0.60696891 0.60032151]
 [0.3395602  0.30389886 0.6399809 ]]
2 th iteration  [[0.20296752 0.60721047 0.60050432]
 [0.34050618 0.30418142 0.64019277]]
3 th iteration  [[0.20375323 0.60744436 0.60068203]
 [0.34140742 0.30445529 0.64039889]]
4 th iteration  [[0.20450163 0.6076707  0.6008546 ]
 [0.34226708 0.30472059 0.64059921]]
5 th iteration  [[0.2052153  0.60788965 0.60102203]
 [0.34308803 0.3049775  0.64079372]]
6 th iteration  [[0.20589658 0.60810141 0.60118437]
 [0.34387285 0.30522623 0.64098245]]
7 th iteration  [[0.20654761 0.60830618 0.60134169]
 [0.34462391 0.305467   0.6411655 ]]
8 th iteration  [[0.20717032 0.60850419 0.6014941 ]
 [0.34534338 0.30570006 0.64134298]]
9 th iteration  [[0.20776649 0.60869566 0.60164171]
 [0.34603322 0.30592567 0.641515  ]]
10 th iteration  [[0.20833777 0.60888081 0.60178465]
 [0.34669525 0.30614408 0.64168172]]
11 th iteration  [[0